export const LOADING = 'LOADING';
export const ERROR = 'ERROR';
export const SET_LOADING = 'SET_LOADING';
//Formulario Action

export const SET_ERROR = 'SET_ERROR';
export const LOADING_USER = 'LOADING_USER';
export const devUrl = 'https://rest.coinapi.io';
export const SET_ERROR_LOGIN = 'SET_ERROR_LOGIN';
export const SET_SELECTED_INDEX = 'SET_SELECTED_INDEX';


//PRODUCT ACTION 
export const GET_PRODUCTS = 'GET_PRODUCT';
export const ERROR_PRODUCT = 'ERROR_PRODUCT';
export const SELECT_EDIT = "SELECT_EDIT";
export const OPEN_FORMULARIO_PRODUCTO = 'OPEN_FORMULARIO_PRODUCTO';
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const CERRAR_MENSAJE_PRODUCTO = 'CERRAR_MENSAJE_PRODUCTO';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const ERROR_PRODUCT_OPERATION = 'ERROR_PRODUCT_OPERATION';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';


//LOGIN ACTION 
export const LOGOUT = 'LOGOUT';
export const GET_USER_LOGIN = 'GET_USER_LOGIN';



//HOME ACTION
export const GET_ALL_CRIPTO = "GET_ALL_CRIPTO";
export const ERROR_CRIPTO = "ERROR_CRIPTO";
export const GET_EXCHANGE_RATE = "GET_EXCHANGE_RATE";
export const SET_LOADING_RATE = "SET_LOADING_RATE";
export const OPEN_VIEW_RATE = 'OPEN_VIEW_RATE';



//  EXCHANGE ACTION

export const GET_ALL_EXCHANGE = "GET_ALL_EXCHANGE";
export const ERROR_EXCHANGE = "ERROR_EXCHANGE";
export const GET_RATE = "GET_RATE";
export const SET_MODAL_CONFIRMACION = "SET_MODAL_CONFIRMACION";
export const SET_SELECT_EXCHANGE = "SET_SELECT_EXCHANGE";

export const LOADING_EXCHANGE_RATE = "LOADING_EXCHANGE_RATE";

//OPERACION ACTION 
export const COMPRAR_MONEDA = "COMPRAR_MONEDA";
export const VIEW_OPERACION = "VIEW_OPERACION";
export const CERRAR_MENSAJE_OPERACION = "CERRAR_MENSAJE_OPERACION";
export const GET_SELECT_OPERACION ="GET_SELECT_OPERACION";

